# Setup test modules
modules:
  - name: "Loading"
    function: loading
    chosen_binary_test_output:
      - mol_pred_loaded
      - mol_cond_loaded
    rename_outputs:
      mol_pred_loaded: "MOL_PRED loaded"
      mol_cond_loaded: "MOL_COND loaded"

  - name: "Chemistry"
    function: rdkit_sanity
    chosen_binary_test_output:
      - passes_rdkit_sanity_checks
    rename_outputs:
      passes_rdkit_sanity_checks: "Sanitization"

  - name: "Chemistry"
    function: inchi_convertible
    chosen_binary_test_output:
      - inchi_convertible
    rename_outputs:
      inchi_convertible: "InChI convertible"

  - name: "Chemistry"
    function: atoms_connected
    chosen_binary_test_output:
      - all_atoms_connected
    rename_outputs:
      all_atoms_connected: "All atoms connected"

  - name: "Geometry"
    function: "distance_geometry"
    parameters:
      bound_matrix_params:
        set15bounds: True # topology based bounds also for 1,5- not just until 1,4-
        scaleVDW: True # scale down lower bounds for atoms less than 5 bonds apart
        doTriangleSmoothing: True
        useMacrocycle14config: False
      threshold_bad_bond_length: 0.25 # widens DG bound by this factor
      threshold_bad_angle: 0.25 # widens DG bound by this factor
      threshold_clash: 0.3 # widens DG bound by this factor
      ignore_hydrogens: True # ignore hydrogens
      sanitize: True # sanitize molecule before running DG module (recommended)
    chosen_binary_test_output:
      - bond_lengths_within_bounds
      - bond_angles_within_bounds
      - no_internal_clash
    rename_outputs:
      bond_lengths_within_bounds: "Bond lengths"
      bond_angles_within_bounds: "Bond angles"
      no_internal_clash: "Internal steric clash"

  - name: "Ring flatness"
    function: "flatness"
    parameters:
      flat_systems: # list atoms which together should lie on plane as SMARTS matches
        aromatic_5_membered_rings_sp2: "[ar5^2]1[ar5^2][ar5^2][ar5^2][ar5^2]1"
        aromatic_6_membered_rings_sp2: "[ar6^2]1[ar6^2][ar6^2][ar6^2][ar6^2][ar6^2]1"
      threshold_flatness: 0.25 # max distance in A to closest shared plane
    chosen_binary_test_output:
      - flatness_passes
    rename_outputs:
      num_systems_checked: number_aromatic_rings_checked
      num_systems_passed: number_aromatic_rings_pass
      max_distance: aromatic_ring_maximum_distance_from_plane
      flatness_passes: "Aromatic ring flatness"

  - name: "Ring non-flatness"
    function: "flatness"
    parameters:
      check_nonflat: True
      flat_systems: # list atoms which together should definitely not lie on plane as SMARTS matches
        non-aromatic_6_membered_rings: "[C,O,S,N;R1]~1[C,O,S,N;R1][C,O,S,N;R1][C,O,S,N;R1][C,O,S,N;R1][C,O,S,N;R1]1"
        non-aromatic_6_membered_rings_db03_0: "[C;R1]~1[C;R1][C,O,S,N;R1]~[C,O,S,N;R1][C;R1][C;R1]1"
        non-aromatic_6_membered_rings_db03_1: "[C;R1]~1[C;R1][C;R1]~[C;R1][C,O,S,N;R1][C;R1]1"
        non-aromatic_6_membered_rings_db02_0: "[C;R1]~1[C;R1][C;R1][C,O,S,N;R1]~[C,O,S,N;R1][C;R1]1"
        non-aromatic_6_membered_rings_db02_1: "[C;R1]~1[C;R1][C,O,S,N;R1][C;R1]~[C;R1][C;R1]1"
      threshold_flatness: 0.05 # minimally required distance in A of at least one atom from the closest shared plane
    chosen_binary_test_output:
      - flatness_passes
    rename_outputs:
      num_systems_checked: number_non-aromatic_rings_checked
      num_systems_passed: number_non-aromatic_rings_pass
      max_distance: non-aromatic_ring_maximum_distance_from_plane
      flatness_passes: "Non-aromatic ring non-flatness"

  - name: "Double bond flatness"
    function: "flatness"
    parameters:
      flat_systems: # list atoms which together should lie on plane as SMARTS matches
        trigonal_planar_double_bonds: "[C;X3;^2](*)(*)=[C;X3;^2](*)(*)"
      threshold_flatness: 0.25 # max distance in A to closest shared plane
    chosen_binary_test_output:
      - flatness_passes
    rename_outputs:
      num_systems_checked: number_double_bonds_checked
      num_systems_passed: number_double_bonds_pass
      max_distance: double_bond_maximum_distance_from_plane
      flatness_passes: "Double bond flatness"

  - name: "Energy ratio"
    function: energy_ratio
    parameters:
      threshold_energy_ratio: 100.0
      ensemble_number_conformations: 50
    chosen_binary_test_output:
      - energy_ratio_passes
    rename_outputs:
      energy_ratio_passes: "Internal energy"

  - name: "Distance to protein"
    function: "intermolecular_distance"
    parameters:
      radius_type: vdw
      radius_scale: 1.0
      clash_cutoff: 0.75
      ignore_types:
        - hydrogens
        - organic_cofactors
        - inorganic_cofactors
        - waters
      max_distance: 5.0
    chosen_binary_test_output:
      - not_too_far_away
      - no_clashes
    rename_outputs:
      not_too_far_away: "Protein-ligand maximum distance"
      no_clashes: "Minimum distance to protein"
    rename_suffix: "_protein"

  - name: "Distance to organic cofactors"
    function: "intermolecular_distance"
    parameters:
      radius_type: vdw
      radius_scale: 1.0
      clash_cutoff: 0.75
      ignore_types:
        - hydrogens
        - protein
        - inorganic_cofactors
        - waters
      max_distance: 5.0
    chosen_binary_test_output:
      - no_clashes
    rename_outputs:
      no_clashes: "Minimum distance to organic cofactors"
    rename_suffix: "_organic_cofactors"

  - name: "Distance to inorganic cofactors"
    function: "intermolecular_distance"
    parameters:
      radius_type: covalent
      radius_scale: 1.0
      clash_cutoff: 0.75
      ignore_types:
        - hydrogens
        - protein
        - organic_cofactors
        - waters
      max_distance: 5.0
    chosen_binary_test_output:
      - no_clashes
    rename_outputs:
      no_clashes: "Minimum distance to inorganic cofactors"
    rename_suffix: "_inorganic_cofactors"

  - name: "Distance to waters"
    function: "intermolecular_distance"
    parameters:
      radius_type: vdw
      radius_scale: 1.0
      clash_cutoff: 0.75
      ignore_types:
        - hydrogens
        - protein
        - organic_cofactors
        - inorganic_cofactors
      max_distance: 5.0
    chosen_binary_test_output:
      - no_clashes
    rename_outputs:
      no_clashes: "Minimum distance to waters"
    rename_suffix: "_waters"

  - name: "Volume overlap with protein"
    function: volume_overlap
    parameters:
      clash_cutoff: 0.075
      vdw_scale: 0.8
      ignore_types:
        - hydrogens
        - organic_cofactors
        - inorganic_cofactors
        - waters
    chosen_binary_test_output:
      - no_volume_clash
    rename_outputs:
      volume_overlap: "volume_overlap_protein"
      no_volume_clash: "Volume overlap with protein"
    rename_suffix: "_protein"

  - name: "Volume overlap with organic cofactors"
    function: volume_overlap
    parameters:
      clash_cutoff: 0.075
      vdw_scale: 0.8
      ignore_types:
        - hydrogens
        - protein
        - inorganic_cofactors
        - waters
    chosen_binary_test_output:
      - no_volume_clash
    rename_outputs:
      volume_overlap: "volume_overlap_organic_cofactors"
      no_volume_clash: "Volume overlap with organic cofactors"
    rename_suffix: "_organic_cofactors"

  - name: "Volume overlap with inorganic cofactors"
    function: volume_overlap
    parameters:
      clash_cutoff: 0.075
      vdw_scale: 0.5
      ignore_types:
        - hydrogens
        - protein
        - organic_cofactors
        - waters
    chosen_binary_test_output:
      - no_volume_clash
    rename_outputs:
      volume_overlap: "volume_overlap_inorganic_cofactors"
      no_volume_clash: "Volume overlap with inorganic cofactors"
    rename_suffix: "_inorganic_cofactors"

  - name: "Volume overlap with waters"
    function: volume_overlap
    parameters:
      clash_cutoff: 0.075
      vdw_scale: 0.5
      ignore_types:
        - hydrogens
        - protein
        - organic_cofactors
        - inorganic_cofactors
    chosen_binary_test_output:
      - no_volume_clash
    rename_outputs:
      volume_overlap: "volume_overlap_waters"
      no_volume_clash: "Volume overlap with waters"
    rename_suffix: "_waters"

# Options for loading molecule files with RDKit
loading:
  mol_pred:
    cleanup: False
    sanitize: False
    add_hs: False
    assign_stereo: False
    load_all: True
  mol_true:
    cleanup: False
    sanitize: False
    add_hs: False
    assign_stereo: False
    load_all: True
  mol_cond:
    cleanup: False
    sanitize: False
    add_hs: False
    assign_stereo: False
    proximityBonding: False
